sudo: required

services:
  - docker

before_install:
  - docker pull truffle/ci

jobs:
  include:
    - stage: local-tests
        - >
          if [ "$TRAVIS_PULL_REQUEST" != "false" ];
          then
            tc use $( basename ${TRAVIS_REPO_SLUG} ):${TRAVIS_PULL_REQUEST_BRANCH};
          fi
        - >
          tc test $( basename ${TRAVIS_REPO_SLUG} ) ~~ $( basename ${TRAVIS_REPO_SLUG} )
    - stage: upstream-tests
      script:
        - >
          if [ "$TRAVIS_PULL_REQUEST" != "false" ];
          then
            tc use truffle-core:$TRAVIS_BRANCH $( basename ${TRAVIS_REPO_SLUG} ):${TRAVIS_PULL_REQUEST_BRANCH};
          fi
        - >
          tc test truffle-core ~~ $( basename ${TRAVIS_REPO_SLUG} )
    - stage: scenario-tests
      script:
        - >
          if [ "$TRAVIS_PULL_REQUEST" != "false" ];
          then
            tc use truffle:$TRAVIS_BRANCH $( basename ${TRAVIS_REPO_SLUG} ):${TRAVIS_PULL_REQUEST_BRANCH};
          fi
        - >
          tc test truffle
