sudo: required

services:
  - docker

before_install:
  - docker pull truffle/ci

jobs:
  include:
    - stage: Repository Tests
      script:
        - >
          if [ "$TRAVIS_PULL_REQUEST" != "false" ];
          then
          docker run -it --rm --name repo-tests \
            truffle/ci:latest run_repo_tests \
              $( basename ${TRAVIS_REPO_SLUG} ) \
              ${TRAVIS_BRANCH} \
              ${TRAVIS_PULL_REQUEST_BRANCH};
          fi
    - stage: Upstream Tests
      script:
        - >
          if [ "$TRAVIS_PULL_REQUEST" != "false" ];
          then
          docker run -it --rm --name upstream-tests \
            truffle/ci:latest run_upstream_tests \
              $( basename ${TRAVIS_REPO_SLUG} ) \
              ${TRAVIS_BRANCH} \
              ${TRAVIS_PULL_REQUEST_BRANCH};
          fi
    - stage: Scenario Tests
      script:
        - >
          if [ "$TRAVIS_PULL_REQUEST" != "false" ];
          then
          docker run -it --rm --name scenario-tests \
            truffle/ci:latest run_scenario_tests \
              $( basename ${TRAVIS_REPO_SLUG} ) \
              ${TRAVIS_BRANCH} \
              ${TRAVIS_PULL_REQUEST_BRANCH};
          fi
